#!/usr/bin/env python

import argparse
import numpy
import os
import sys
#import numexpr as ne
#import math
#import csv
#import time
#import pandas
#import itertools


PI = 3.141592653589793115997963468544
error = 1e-10

def DirectoryCheck (path):
	dirPath = ""

	if not (os.path.isdir(os.path.dirname(path))):
		os.makedirs(os.path.dirname(path))
	return
	
	for level in filter (bool, path.split("/")):
		dirPath += level + "/"
		
		if (level != ".." and level != "."):
			directory = os.path.dirname(dirPath)

			try:
				os.stat(directory)
			except:
				os.mkdir(directory)

	return

def GenerateRandom (n):
	CartesianPoints = numpy.random.normal (0.0, 1.0, (n, 3))
	return numpy.sqrt (numpy.einsum('...i, ...i', CartesianPoints, CartesianPoints))




parser = argparse.ArgumentParser(description="Create a sky of stars.")

parser.add_argument("OutputDir", help="Path to the directory where the data will be output.")
parser.add_argument("AngularSampling", help="Method of angular sampling of stars:\n\t\"Random\" - random points on the unit sphere.")
# parser.add_argument("N", help="Number of stars to be generated.")




args = parser.parse_args()

outputDirectory = args.OutputDir

if (outputDirectory[-1] != "/"):
	outputDirectory += "/"

if not (os.path.isdir(os.path.dirname(outputDirectory))):
	try:
		os.makedirs(os.path.dirname(outputDirectory))
	except:
		print "Error: Output directory is not a valid path."
		sys.exit(1)

	if not os.access(outputDirectory, os.W_OK):
		print "Error: You do not have rights at the output directory"
		sys.exit(1)

samplingMethod = args.AngularSampling

methods = ["Random", "Regular", "Milky Way", "Galaxy"]








dataFile = "StarPositions.dat"

if os.path.isfile(dataFile):
	print "Output data file already exists. Please specify a different output directory."
	sys.exit(1)

readMeFIle = "README"








nStars = 20
method = "Random"

print (GenerateRandom (nStars))


